# -*- coding: utf-8 -*-
"""Pro108.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixjV-hUjMjktijvLDfEEKf_qbH-7Y2B8
"""

import pandas as pd
import csv
import plotly.figure_factory as ff

df=pd.read_csv('data.csv')
fig=ff.create_distplot([df['Avg Rating'].tolist()],['Avg Rating'],show_hist=False)

fig.show()